trialsToRunPerPlan: 50000
cycleTimes: "2, 7, 7, 1, 2, 10, 6, 8, 16, 9, 10, 13, 13, 14, 15, 11, 9, 9, 20, 21, 16, 20, 21, 4, 21, 21, 22, 27, 27"
cycleTimesVariationMin: 90
cycleTimesVariationMax: 125
itemsToEstimate: 8
itemsToEstimateVariationMin: 110
itemsToEstimateVariationMax: 125
parallelismFactorVariationMin: 90
parallelismFactorVariationMax: 120
startDate: "2023-06-10"
parallelismFactor: 8.5
acceptableConfidence: 85
centralTendency: "median"
